#cloud-config
# Cloud config for Jenkins servers

runcmd:
# Install Docker
- apt install dirmngr
- curl -sSL https://get.docker.com | sudo sh
# Create and set permissions for Jenkins mount directory
- wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add -
- echo deb http://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list
- sudo apt-get update
- sudo apt-get install jenkins
- sudo systemctl start jenkins
